default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 1234
  host: localhost

development:
  <<: *default
  database: postgres1

test:
  <<: *default
  database: postgres1

production:
  <<: *default
  database: postgres1